OpenSearch Rock
canonical/opensearch-rock pull request #1
Opened 2023-03-07 21:39 UTC by Mehdi-Bendriss

## Issue
This PR addresses [DPE-1357](https://warthogs.atlassian.net/browse/DPE-1357) & [DPE-1358](https://warthogs.atlassian.net/browse/DPE-1358). Namely this PR addresses the following:
- Implementation of the Rock based on the opensearch snap
  - entrypoint provided since we do not have a K8s charm yet
  - opensearch security disabled, as it will be handled by the charm
- integration tests simulating a 3 nodes cluster 
- ci / cd pipeline

2023-03-08 10:59 UTC, taurus-forever commented on .github/workflows/ci.yaml
> +          sudo apt-get update
why are you updating apt metadata if you install app components from snap?

2023-03-08 10:59 UTC, taurus-forever commented on .github/workflows/ci.yaml
> +          fi
Duplicate of lines 140-144?

2023-03-08 10:59 UTC, taurus-forever commented on .github/workflows/on_push.yaml
> +      - feature/**
May I learn about those branch naming?

2023-03-08 10:59 UTC, taurus-forever commented on .github/workflows/release.yaml
> +          sudo apt-get update
no apt packages in use. Is it necessary here?

2023-03-08 10:59 UTC, taurus-forever commented on .github/workflows/release.yaml
> +          docker push "charmed/opensearch:${{env.VERSION}}"
Just today @jnsgruk told us to avoid publishing of new imaged to hub.docker.com and use GitHub-repo specific docker regestry: https://ghcr.io/canonical/opensearch:${{env.VERSION}}

You can find the example here https://github.com/canonical/prometheus-rock/pkgs/container/prometheus

2023-03-08 10:59 UTC, taurus-forever commented on README.md
> +**NOTE:** This deployment IS NOT suitable for production as this deployment disables and does NOT configure the security of OpenSearch.
```suggestion
**NOTE:** This deployment IS NOT suitable for production AS IS as this deployment disables and does NOT configure the security of OpenSearch. Please use Juju charm "[opensearch-k8s](https://charmhub.io/opensearch-k8s)" to deploy it securely.
```

As we will use it in production after charm.py re-configuration. :-)

2023-03-08 12:32 UTC, delgod requested changes

2023-03-08 12:32 UTC, delgod commented on scripts/start.sh
> +/usr/bin/setpriv \
let's avoid forking
```suggestion
exec /usr/bin/setpriv \
```

2023-03-08 18:12 UTC, jardon commented on .github/workflows/ci.yaml
> +  VERSION: 2.6.0
Can we use `yq` to pull the version out of the `rockcraft.yaml` so we dont have to update this?

2023-03-08 18:12 UTC, jardon commented on .github/workflows/on_push.yaml
> +      - feature/**
I looks to me like the idea is using a `push` event to run testing, but it makes more sense to me for that to be on a `pull_request` event instead.

2023-03-09 09:58 UTC, Mehdi-Bendriss commented on .github/workflows/ci.yaml
> +          sudo apt-get update
Bad residue of a previous step copypast

2023-03-09 10:01 UTC, Mehdi-Bendriss commented on .github/workflows/on_push.yaml
> +      - feature/**
Yes, so the idea here is to have a branch where the CI can run for testing. I find it useful to have a test environment while actively working on a feature and prior to making a PR. (I removed the `track/*` and kept `feature/*`)

2023-03-09 10:03 UTC, Mehdi-Bendriss commented on README.md
> +**NOTE:** This deployment IS NOT suitable for production as this deployment disables and does NOT configure the security of OpenSearch.
Good point, thank you! I adjusted your message a bit, as we currently do not have yet a K8s charm (the one linked is not by us) - what do you think?

2023-03-09 10:13 UTC, Mehdi-Bendriss commented on .github/workflows/ci.yaml
> +  VERSION: 2.6.0
that's a good idea

2023-03-09 12:22 UTC, delgod approved these changes

2023-03-10 09:09 UTC, taurus-forever commented on .github/workflows/ci.yaml
> +          sudo snap install yq
Just a nitpicking, snap allow to intall several packages at once (in a confined mode):
```
> sudo snap install jq yq
yq v4.31.2 from Mike Farah (mikefarah) installed
jq 1.5+dfsg-1 from Michael Vogt (mvo✪) installed
```

2023-03-10 09:09 UTC, taurus-forever commented on rockcraft.yaml
> +name: opensearch  # the name of your ROCK
charmed-opensearch?

2023-03-10 09:09 UTC, taurus-forever commented on .github/workflows/release.yaml
> +          docker push ghcr.io/canonical/charmed-opensearch:${version}
I am slightly lost here, what is `canonical/charmed-opensearch` (GH shows 404 for me).
The current repo is `opensearch-rock`, consider to rename it to `charmed-opensearch-rock`.
BTW, what about ROCK name [here](https://github.com/canonical/opensearch-rock/pull/1/files#diff-67c464bbed217d3d422ddd2db32d89360c18ce8584542858e61f3f842c6fb432R3)?

@delgod do you want to push ROCK imaged into 'charm' repo/registry `canonical/opensearch` OR into the current repo/registry `canonical/opensearch-rock`. IMHO, current, OCI image should stay in the same GitHub repo where Dockerfile/rockcraft.yaml is located. Otherwise it will be a mess on a distance.

2023-03-10 13:40 UTC, Mehdi-Bendriss commented on .github/workflows/release.yaml
> +          docker push ghcr.io/canonical/charmed-opensearch:${version}
@taurus-forever - for #1 - I renamed the repo and artifacts to having the `charmed-opensearch-*` prefix

2023-03-10 16:10 UTC, jardon approved these changes

2023-03-10 16:10 UTC, jardon commented on .github/workflows/release.yaml
> +          version="$(cat rockcraft.yaml | yq .version)"
I have the same question about image tagging that we have in other products on whether it should be tagged as `<version>` or `<version>-<base>_<risk>`, but that is non-blocking imo for this PR.

2023-03-10 16:10 UTC, jardon commented on .github/workflows/ci.yaml
> +  test:
Non-blocking comment, but it would be nice to be able to easily run these tests locally instead of having to rely on GH Actions CI.

2023-03-10 16:10 UTC, jardon commented on .github/workflows/ci.yaml
> +on:
I like putting `workflow_dispatch` as a trigger on most CI workflows to allow re-running without having to open a PR or pushing to a branch.

This is a preference, not a requirement.

2023-03-10 16:14 UTC, taurus-forever requested changes

2023-03-10 16:14 UTC, taurus-forever commented on .github/workflows/release.yaml
> +          docker push ghcr.io/canonical/charmed-opensearch-rock:${version}
As discussed, apologies, but revert: 
```suggestion
          docker push ghcr.io/canonical/charmed-opensearch:${version}
```

2023-03-10 17:17 UTC, jardon requested changes

2023-03-10 17:17 UTC, jardon commented on .github/workflows/release.yaml
> +              docker-daemon:charmed-opensearch:${version}
```suggestion
              docker-daemon:ghcr.io/charmed-opensearch:${version}
```
Played around with this on another repo.  I suffered so you dont have to.

2023-03-10 17:17 UTC, jardon commented on .github/workflows/release.yaml
> +              docker-daemon:charmed-opensearch:${version}
You'll likely run into this [issue](https://stackoverflow.com/questions/69014742/github-denied-permission-denied-write-package) as well.  Someone with admin will need to change the permissions. @taurus-forever ?

2023-03-10 18:08 UTC, Mehdi-Bendriss commented on .github/workflows/release.yaml
> +          version="$(cat rockcraft.yaml | yq .version)"
I had a discussion with Alex, it should be: `<version>-<base>_<risk>`. Basically:
```
base=($(cat rockcraft.yaml | yq .base | tr ":" "\n"))
base=$base[2]
tag_version="${version}-${base}_${{ env.RELEASE }}"
```

2023-03-10 18:09 UTC, Mehdi-Bendriss commented on .github/workflows/ci.yaml
> +  test:
i pushed my test script

2023-03-11 00:47 UTC, taurus-forever commented on .github/workflows/release.yaml
> +              docker-daemon:charmed-opensearch:${version}
GHCR_TOKEN secret added here and to mongodb-rock, please try it from your side.

2023-03-11 00:52 UTC, taurus-forever approved these changes

2023-03-12 15:32 UTC, Mehdi-Bendriss commented on .github/workflows/release.yaml
> +              docker-daemon:charmed-opensearch:${version}
@taurus-forever I think using the `GITHUB_TOKEN` with `admin` permissions may suffice, [for reference](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-in-a-github-actions-workflow)
> You can use a GITHUB_TOKEN in a GitHub Actions workflow to delete or restore a package using the REST API, if the token has admin permission to the package. Repositories that publish packages using a workflow, and repositories that you have explicitly connected to packages, are automatically granted admin permission to packages in the repository.

2023-03-13 16:36 UTC, jardon approved these changes

2023-03-13 18:48 UTC, merged